window.HAVEN_DATA = {
  "siteTitle": "高天通訊處早會課程",
  "unitName": "高天通訊處",
  "brandName": "HAVEN",
  "monthTitle": "2026 年 8 月課程表",
  "morningTime": "08:30–09:10",
  "quote": "今天的努力，是明天選擇人生的底氣。",
  "announcement": "課程內容如有異動，請以當日公告為準。",
  "schedule": [
    {
      "week": 1,
      "date": "2026-08-03",
      "weekday": "星期一",
      "host": "林昱勛 SP、鄭伃涵",
      "finance": "娛樂｜陳昆郁 專員",
      "course": "榮譽績效分享",
      "speaker": "詹政杰 主任",
      "practice": "敲門磚",
      "practiceLead": "許智雄 經理",
      "meeting": "主管會議 14:00–16:00（6A 小教室）"
    },
    {
      "week": 1,
      "date": "2026-08-04",
      "weekday": "星期二",
      "host": "林昱勛 SP、鄭伃涵",
      "finance": "健康生活｜吳亦婷 主任",
      "course": "醫療前中後＋全險觀念",
      "speaker": "蕭宇晴 主任",
      "practice": "理財型議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 1,
      "date": "2026-08-05",
      "weekday": "星期三",
      "host": "林昱勛 SP、鄭伃涵",
      "finance": "保險議題｜劉佩蓉 專員",
      "course": "NPSS－銷售面談",
      "speaker": "謝政男 襄理",
      "practice": "醫療議題",
      "practiceLead": "謝政男 襄理",
      "meeting": ""
    },
    {
      "week": 1,
      "date": "2026-08-06",
      "weekday": "星期四",
      "host": "林昱勛 SP、鄭伃涵",
      "finance": "保險議題｜何廷軒 專員",
      "course": "產險理賠會說話｜實務案例分享",
      "speaker": "何廷軒 專員",
      "practice": "增員工具",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 1,
      "date": "2026-08-07",
      "weekday": "星期五",
      "host": "林昱勛 SP、鄭伃涵",
      "finance": "稅務｜李竑諺 主任",
      "course": "H 小組案例研討",
      "speaker": "陳懷柔 主任",
      "practice": "－",
      "practiceLead": "",
      "meeting": "未達 3C 會議 11:00–12:00"
    },
    {
      "week": 2,
      "date": "2026-08-10",
      "weekday": "星期一",
      "host": "詹政杰 SP、莊詠崴",
      "finance": "娛樂｜施昱廷 主任",
      "course": "榮譽績效分享",
      "speaker": "吳睿綝 襄理",
      "practice": "敲門磚",
      "practiceLead": "陳懷柔 主任",
      "meeting": ""
    },
    {
      "week": 2,
      "date": "2026-08-11",
      "weekday": "星期二",
      "host": "詹政杰 SP、莊詠崴",
      "finance": "健康生活｜呂侑恩 專員",
      "course": "市場調查訪談表",
      "speaker": "吳亦婷 專員",
      "practice": "理財型議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 2,
      "date": "2026-08-12",
      "weekday": "星期三",
      "host": "詹政杰 SP、莊詠崴",
      "finance": "保險議題｜詹政杰 主任",
      "course": "NPSS－需求分析",
      "speaker": "施昱廷 主任",
      "practice": "醫療議題",
      "practiceLead": "許智雄 經理",
      "meeting": ""
    },
    {
      "week": 2,
      "date": "2026-08-13",
      "weekday": "星期四",
      "host": "詹政杰 SP、莊詠崴",
      "finance": "財經時事｜曾馨慧 主任",
      "course": "現實人生 Part 2",
      "speaker": "何宜庭 襄理",
      "practice": "增員工具",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 2,
      "date": "2026-08-14",
      "weekday": "星期五",
      "host": "詹政杰 SP、莊詠崴",
      "finance": "稅務｜陳昆郁 專員",
      "course": "H 小組案例研討",
      "speaker": "蕭宇晴 主任",
      "practice": "－",
      "practiceLead": "",
      "meeting": "未達 3C 會議 11:00–12:00"
    },
    {
      "week": 3,
      "date": "2026-08-17",
      "weekday": "星期一",
      "host": "李竑諺 SP、潘彥均",
      "finance": "娛樂｜劉佩蓉 專員",
      "course": "榮譽績效分享",
      "speaker": "謝政男 襄理",
      "practice": "敲門磚",
      "practiceLead": "蕭宇晴 主任",
      "meeting": "主管會議 14:00–16:00（6A 小教室）"
    },
    {
      "week": 3,
      "date": "2026-08-18",
      "weekday": "星期二",
      "host": "李竑諺 SP、潘彥均",
      "finance": "健康生活｜何廷軒 專員",
      "course": "Call 進百萬團險",
      "speaker": "高彪、陳怡璇 經理",
      "practice": "理財型議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 3,
      "date": "2026-08-19",
      "weekday": "星期三",
      "host": "李竑諺 SP、潘彥均",
      "finance": "保險議題｜吳亦婷 主任",
      "course": "新商品搶先聽",
      "speaker": "蕭宇晴 主任／王思涵 主任",
      "practice": "醫療議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 3,
      "date": "2026-08-20",
      "weekday": "星期四",
      "host": "李竑諺 SP、潘彥均",
      "finance": "財經時事｜李竑諺 主任",
      "course": "打造多源收益的分紅帳戶",
      "speaker": "陳懷柔 主任",
      "practice": "增員工具",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 3,
      "date": "2026-08-21",
      "weekday": "星期五",
      "host": "李竑諺 SP、潘彥均",
      "finance": "稅務｜施昱廷 主任",
      "course": "生命靈數",
      "speaker": "何宜家 處經理",
      "practice": "－",
      "practiceLead": "",
      "meeting": "未達 3C 會議 11:00–12:00"
    },
    {
      "week": 4,
      "date": "2026-08-24",
      "weekday": "星期一",
      "host": "蕭宇晴 SP、馬烝偉",
      "finance": "娛樂｜呂侑恩 專員",
      "course": "博田健康大講堂",
      "speaker": "博田專任醫師",
      "practice": "敲門磚",
      "practiceLead": "蕭如菁 經理",
      "meeting": ""
    },
    {
      "week": 4,
      "date": "2026-08-25",
      "weekday": "星期二",
      "host": "蕭宇晴 SP、馬烝偉",
      "finance": "健康生活｜詹政杰 主任",
      "course": "榮譽績效分享",
      "speaker": "何宜庭 襄理",
      "practice": "理財型議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 4,
      "date": "2026-08-26",
      "weekday": "星期三",
      "host": "蕭宇晴 SP、馬烝偉",
      "finance": "保險議題｜曾馨慧 主任",
      "course": "團險宣導",
      "speaker": "黃以瑟 專員",
      "practice": "醫療議題",
      "practiceLead": "",
      "meeting": ""
    },
    {
      "week": 4,
      "date": "2026-08-27",
      "weekday": "星期四",
      "host": "蕭宇晴 SP、馬烝偉",
      "finance": "財經時事｜陳昆郁 專員",
      "course": "用一隻手機創造合作業績",
      "speaker": "許智雄 經理",
      "practice": "－",
      "practiceLead": "",
      "meeting": "未達 3C 會議 11:00–12:00"
    },
    {
      "week": 4,
      "date": "2026-08-28",
      "weekday": "星期五",
      "host": "蕭宇晴 SP、馬烝偉",
      "finance": "稅務｜劉佩蓉 專員",
      "course": "H 小組案例研討",
      "speaker": "何宜家 處經理",
      "practice": "－",
      "practiceLead": "",
      "meeting": ""
    }
  ]
};
